// Regenerates src/core/codecs/webp-wasm-{dec,enc}.ts: libwebp's WASM, base64'd into a
// TypeScript module. Run after bumping @jsquash/webp. See features/codec-webp.md.
//
// WHY THE BYTES ARE INLINED, which looks absurd until you try the alternatives.
//
// jSquash is browser-first. Its Emscripten glue locates the .wasm relative to
// `import.meta.url` and fetches it, and its Node branch is a stub that throws "not
// implemented... yet...". Measured, on this machine, during the spike codec-webp.md asked
// for:
//
//   Bun            works -- Bun's fetch resolves file:// URLs
//   Node           "fetch failed" -- undici will not fetch file://
//   esbuild bundle "fetch failed" -- the .wasm is not bundled, and import.meta.url now
//                  points at the bundle, so the path it builds does not exist
//
// That last one is the one that matters: an Obsidian plugin IS an esbuild bundle, a single
// main.js with no .wasm shipped beside it. Every fix that keeps the .wasm as a separate
// file fails there, and the ones that do not (ship the .wasm and read it through Obsidian's
// vault adapter) push plugin-specific work into every consumer.
//
// The glue accepts a `wasmBinary` override, which works in all three. So the only question
// left is where the bytes come from, and the answer that needs nothing from the
// environment -- no fs, no fetch, no import.meta.url, no bundler config -- is "from the
// module itself". That also keeps src/core host-free, which the guard enforces.
//
// The cost is base64's 33%, which gzip only partly gives back (measured: ~137% of the raw
// gzipped size). It is paid ONLY by a caller who touches a WebP, because these modules are
// reached through a dynamic import. Decode and encode are separate files for the same
// reason: a plugin that only ever reads WebP should not carry the encoder.
import { readFile, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const pkg = require.resolve('@jsquash/webp/package.json');
const dir = pkg.slice(0, pkg.lastIndexOf('/'));
const version = JSON.parse(await readFile(pkg, 'utf8')).version;

// SIMD only, on the encode side. libwebp ships both, and jSquash picks between them at
// runtime with wasm-feature-detect -- but shipping both would inline 612 KB to use one of
// them, and every runtime this library targets (Node 22, Bun, Electron 30+) has had SIMD
// for years. If a runtime without it ever turns up, it fails loudly at load rather than
// quietly producing wrong pixels, and CodecLoadError says so.
const TARGETS = [
  { name: 'dec', wasm: `${dir}/codec/dec/webp_dec.wasm`, what: 'the decoder' },
  { name: 'enc', wasm: `${dir}/codec/enc/webp_enc_simd.wasm`, what: 'the SIMD encoder' },
];

for (const { name, wasm, what } of TARGETS) {
  const bytes = await readFile(wasm);
  const b64 = bytes.toString('base64');
  const out = `${process.cwd()}/src/core/codecs/webp-wasm-${name}.ts`;

  await writeFile(
    out,
    `// GENERATED by scripts/gen-wasm.mjs. Do not edit.
//
// libwebp ${what}, from @jsquash/webp@${version}, base64'd. ${(bytes.length / 1024).toFixed(1)} KB of WASM.
// The reasoning for inlining rather than shipping a .wasm beside the JS is in the
// generator; the short version is that an Obsidian plugin is a single esbuild'd main.js
// and every other load path fails there.
//
// Only ever reached through a dynamic import, so a caller who never touches a WebP never
// pays for this file.
//
// The ": string" annotation is load-bearing: without it tsc infers a literal string type
// and emits this entire blob into the .d.ts too, which measured 450 KB of declaration file
// saying nothing a consumer needs.
export const WASM_BASE64: string =
  '${b64}';
`,
    'utf8',
  );
  console.log(`${out.split('/').pop().padEnd(28)} ${(bytes.length / 1024).toFixed(1)} KB -> ${(b64.length / 1024).toFixed(1)} KB base64`);
}
